services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./staticfiles:/code/staticfiles
    expose:
      - 8000  # Exposes the port internally but doesn't map it to the host machine
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_USER=naman"
      - "POSTGRES_PASSWORD=aJaX2025Unibec"
      - "POSTGRES_DB=LibraNet-database"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Nginx listens on port 80 on the host
    depends_on:
      - web

volumes:
  postgres_data: